default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: redited_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: redited_test
  username: postgres
  password: postgres
